### ISSUE TITLE
Installation via Anaconda?

### ISSUE THREAD

**Issue by Olivercomputing** [CORE-GATECH-GROUP/serpent-tools#330]
## Versions

* Version  from ``serpentTools.__version__``

* Python version - ``python --version``

* IPython or Jupyter version if applicable

**Comment by Olivercomputing** [comment]
As many do, I'm using Anaconda to manage Python packages and virtual environments. I haven't been able to identify a way to using it to install serpentTools. If this is possible, please give details. If not, I think it would be useful to support this mode of installation. Using pip separately from the  Anaconda manager can apparently break an installation.

**Comment by drewejohnson** [comment]
Thanks for pointing this out. I have started making a conda recipe that would make this easier, but haven't picked it up in a while.

As I don't use anaconda to manage serpentTools, I will have to try and play around with some options. Since this is a pure python package, e.g. no compiled C / fortran included, my first reaction is there is probably a straight forward way to do this, even without having it hosted on the `conda-forge`.

> I haven't been able to identify a way to using it to install serpentTools

Can you explain what you have attempted so far? Looking at https://github.com/ContinuumIO/anaconda-issues/issues/1429, you might be able to use pip **if** you have a conda-managed pip, e.g.
```
conda activate my-env
conda install pip
...
pip install serpentTools
```

**Comment by Olivercomputing** [comment]
Mostly I searched for serpentTools via Conda and couldn't find anything. I'd thought about using pip directly but was concerned about the Anaconda docs mentioning breaking an installation if pip was used rather than conda for package management. What you found in the 1429 issue may alleviate that concern. I do still think that your package should be easily available via the Anaconda system. Pyne is available that way and I'm using their Serpent related functions but it's a miniscule subset of the capabilities in serpentTools.

**Comment by drewejohnson** [comment]
Yeah we don't have an official package that you can install through `conda-forge` like PyNE yet. Your best bet will be to install with the conda-managed pip. You might also want to check out https://www.anaconda.com/understanding-conda-and-pip/, as they mention
>Occasionally a package is needed which is not available as a conda package but is available on PyPI and can be installed with pip. In these cases, it makes sense to try to use both conda and pip. 

Since we don't have any complicated installation procedure, and all the packages we require [numpy, matplotlib, [`yaml`](https://anaconda.org/conda-forge), and six] are all available from the conda-forge, it _should_ be painless.

I'll leave this open for a week to give time for you or other people to raise related concerns

**Comment by drewejohnson** [comment]
Closing. But please reach out if there are further issues.
