### ISSUE TITLE
ENH `version` defined multiple times

### ISSUE THREAD

**Issue by rzehumat** [CORE-GATECH-GROUP/serpent-tools#488]
**Is your feature request related to a problem? Please describe.**
Defining one variable multiple times is bad for code maintainability (DRY principle). The `version` or `__version__` is defined [3 or something times](https://github.com/search?q=repo%3ACORE-GATECH-GROUP%2Fserpent-tools%200.9.5&type=code). 

Of course, sometimes it is inevitable, but I think elegant solution exists here.

**Describe the solution you'd like**
I would follow [this StackOverflow idea](https://stackoverflow.com/a/74608959/13224210). I did not get (yet) the idea about not defining `version` in code at all. Out of the suggested, point (1) looks like a natural solution to this, but there is the issue with minimal Python 3.8.

**Describe alternatives you've considered**
- Keeping multiple definitions of `version` seems unnecessary
- Idea (2) in the abovementioned SO answer is possible, but having code in `pyproject.toml` seems weird to me.
- Of course, the `neither` option (in the SO answer) would be best, but I don't know how to do it yet.

**Additional context**
I could do a PR implementing it.

**Comment by rzehumat** [comment]
EDIT: using the [versioneer tool](https://github.com/python-versioneer/python-versioneer) is an alternative that implements the `neither` option

**Comment by drewejohnson** [comment]
@rzehumat agree, having the same thing defined in multiple places is burdensome. For a while, there weren't great tools to avoid this.

There are three _primary_ places where it's defined and where it should be removed

1. build config files (e.g., `pyproject.toml`, historically `setup.py` or `setup.cfg`)
2. project module file `serpentTools/__init__.py`, and
3. docs configuration file (`docs/conf.py`)

I've used versioneer in the past with good success, and lately am more partial to [`setuptools-scm`](https://github.com/pypa/setuptools_scm/), both of which grab version data based on commits and tags. `seutptools-scm` _might_ provide the "neither" option of not having the package version as a settable attribute (fetching from package metadata instead) but I would need to investigate.

My preference would be the following

1. `setuptools-scm` for handling determining version based off `git` history.
2. `serpentTools.__version__` is set based off some package metadata fetching routine, not a string attribute
3. `docs/conf.py` imports `serpentTools.__version__` for it's versioning needs

If you are able to pick this up. let me know. Otherwise I will try and get around to this after the next release
